import fs from "node:fs";
import path from "node:path";

export type FinancialLayout = {
  sections?: {
    sales?: boolean;
    purchases?: boolean;
    expenses?: boolean;
    netIncome?: boolean;
  };
  showDailyTotals?: boolean;
  showSummaryCards?: boolean;
  header?: { title?: string; position?: "left" | "center" | "right" };
  footer?: { text?: string; position?: "left" | "center" | "right" };
};

const LAYOUT_PATH = path.join(__dirname, "../../prisma/seedData/financialLayout.json");

const DEFAULT_LAYOUT: FinancialLayout = {
  sections: { sales: true, purchases: true, expenses: true, netIncome: true },
  showDailyTotals: true,
  showSummaryCards: true,
  header: { title: "Financial Report", position: "center" },
  footer: { text: "Generated by system", position: "center" },
};

let cache: FinancialLayout | null = null;
let flushTimer: NodeJS.Timeout | null = null;
const FLUSH_DELAY_MS = 500;

function ensureDir() {
  const dir = path.dirname(LAYOUT_PATH);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

export function readFinancialLayout(): FinancialLayout {
  try {
    if (cache) return cache;
    ensureDir();
    if (!fs.existsSync(LAYOUT_PATH)) {
      cache = DEFAULT_LAYOUT;
      return cache;
    }
    const raw = fs.readFileSync(LAYOUT_PATH, "utf-8");
    const data = JSON.parse(raw || "{}");
    cache = { ...DEFAULT_LAYOUT, ...(data || {}) } as FinancialLayout;
    return cache;
  } catch {
    cache = DEFAULT_LAYOUT;
    return cache;
  }
}

export function writeFinancialLayout(next: FinancialLayout): void {
  cache = { ...DEFAULT_LAYOUT, ...(next || {}) } as FinancialLayout;
  ensureDir();
  if (flushTimer) clearTimeout(flushTimer);
  flushTimer = setTimeout(() => {
    try {
      fs.writeFileSync(LAYOUT_PATH, JSON.stringify(cache, null, 2), "utf-8");
    } catch {
      // ignore write errors
    }
  }, FLUSH_DELAY_MS);
}