import fs from "node:fs";
import path from "node:path";

export type FinancialLayout = {
  sections?: {
    sales?: boolean;
    purchases?: boolean;
    expenses?: boolean;
    netIncome?: boolean;
  };
  showDailyTotals?: boolean;
  showSummaryCards?: boolean;
  header?: { title?: string; position?: "left" | "center" | "right" };
  footer?: { text?: string; position?: "left" | "center" | "right" };
};

// Base path for all layout files
const DATA_DIR = path.join(__dirname, "../../prisma/seedData");

const DEFAULT_LAYOUT: FinancialLayout = {
  sections: { sales: true, purchases: true, expenses: true, netIncome: true },
  showDailyTotals: true,
  showSummaryCards: true,
  header: { title: "Financial Report", position: "center" },
  footer: { text: "Generated by system", position: "center" },
};

// In-memory cache: tenantId -> FinancialLayout
const cache = new Map<string, FinancialLayout>();
// Flush timers: tenantId -> Timeout
const flushTimers = new Map<string, NodeJS.Timeout>();
const FLUSH_DELAY_MS = 500;

function ensureDir() {
  if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
}

function getFilePath(tenantId: string) {
  // Sanitize tenantId
  const safeId = tenantId.replace(/[^a-zA-Z0-9-]/g, "");
  // Fallback for legacy global file if tenant is "default" or missing
  if (!safeId || safeId === "default") return path.join(DATA_DIR, "financialLayout.json");
  return path.join(DATA_DIR, `financialLayout_${safeId}.json`);
}

export function readFinancialLayout(tenantId: string): FinancialLayout {
  try {
    if (cache.has(tenantId)) return cache.get(tenantId)!;
    
    ensureDir();
    const filePath = getFilePath(tenantId);
    
    if (!fs.existsSync(filePath)) {
      cache.set(tenantId, DEFAULT_LAYOUT);
      return DEFAULT_LAYOUT;
    }
    
    const raw = fs.readFileSync(filePath, "utf-8");
    const data = JSON.parse(raw || "{}");
    const merged = { ...DEFAULT_LAYOUT, ...(data || {}) } as FinancialLayout;
    
    cache.set(tenantId, merged);
    return merged;
  } catch {
    return DEFAULT_LAYOUT;
  }
}

export function writeFinancialLayout(tenantId: string, next: FinancialLayout): void {
  // Merge with existing
  const current = cache.get(tenantId) || DEFAULT_LAYOUT;
  const merged = { ...current, ...next } as FinancialLayout;
  if (next.sections) merged.sections = { ...current.sections, ...next.sections };
  if (next.header) merged.header = { ...current.header, ...next.header };
  if (next.footer) merged.footer = { ...current.footer, ...next.footer };

  cache.set(tenantId, merged);
  ensureDir();
  
  const timer = flushTimers.get(tenantId);
  if (timer) clearTimeout(timer);
  
  const newTimer = setTimeout(() => {
    try {
      const filePath = getFilePath(tenantId);
      fs.writeFileSync(filePath, JSON.stringify(merged, null, 2), "utf-8");
      flushTimers.delete(tenantId);
    } catch {
      // ignore write errors
    }
  }, FLUSH_DELAY_MS);
  
  flushTimers.set(tenantId, newTimer);
}